version: '3'
services:
  eureka-server:
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    build: ./eurika-server
    networks:
      - app-network

  service-client:
    container_name: service-client
    restart: always
    ports:
      - "8088:8088"
    build:
      context: ./eureka-client
      dockerfile: Dockerfile
    environment:
      - EUREKA_SERVER=eureka-server
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    depends_on:
      - eureka-server
      - mysql
    networks:
      - app-network

  service-voiture:
    container_name: service-voiture
    restart: always
    ports:
      - "8089:8089"
    build:
      context: ./voiture-eureka
      dockerfile: Dockerfile
    environment:
      - EUREKA_SERVER=eureka-server
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    depends_on:
      - eureka-server
      - mysql
    networks:
      - app-network

  mysql:
    container_name: mysql
    image: mysql:latest
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: client
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

volumes:
  mysql:

networks:
  app-network:
    driver: bridge