spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8088/
          predicates:
            - Path=/clients/**
  application:
    name: Gateway
server:
  port: 8888